### ISSUE TITLE
cann't build with command: "cmake -GNinja -S. -Bbuild"

### ISSUE THREAD

**Issue by huyiice** [vllogic/vllink_lite#5]
can not build with the following command in ubuntu : 

cd Vllink_Lite/vsf/project_vllink_lite/vllink_lite/cmake_vllinklite_gd32f350
cmake -GNinja -S. -Bbuild

ERROR LOG:
-- No build type selected, default to Debug
-- The C compiler identification is GNU 9.2.1
-- The CXX compiler identification is GNU 9.2.1
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/arm-none-eabi-gcc
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - failed
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - failed
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:85 (add_subdirectory):
  The source directory

    /home/huyiice/git/Vllink_Lite/vsf

  does not contain a CMakeLists.txt file.

-- Configuring incomplete, errors occurred!
See also "/home/huyiice/git/Vllink_Lite/vsf/project_vllink_lite/vllink_lite/cmake_vllinklite_gd32f350/build/CMakeFiles/CMakeOutput.log".
See also "/home/huyiice/git/Vllink_Lite/vsf/project_vllink_lite/vllink_lite/cmake_vllinklite_gd32f350/build/CMakeFiles/CMakeError.log".

**Comment by talpachen** [comment]
请使用IAR，CMAKE已失去维护
